name: Windows
on: workflow_dispatch

env:
  flutter_version: '3.24.4'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: plum-tech/xiaoying-x
          token: ${{ secrets.MIMIR_GITHUB_TOKEN }}
          fetch-depth: 0

      # Configure Git with PAT for subsequent steps
      # This is the crucial step that sets up global credentials.
      - name: Configure Git for private dependencies
        run: |
          git config --global url."https://${{ secrets.MIMIR_GITHUB_TOKEN }}@github.com/".insteadOf "https://github.com/"

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.flutter_version }}
          channel: stable
          cache: true

      - name: Setup Flutter
        run: |
          flutter config --no-cli-animations

      - name: Build Windows
        run: |
          flutter pub run build_runner build --delete-conflicting-outputs
          dart run msix:create

      - name: Upload building
        uses: actions/upload-artifact@v4
        with:
          name: SITLife-Windows-release
          path: build\windows\x64\runner\Release\SIT-Life.msix
